### ISSUE TITLE
Explore improving efficiency by using smart pointers

### ISSUE THREAD

**Issue by devrieskevin** [devrieskevin/metaheurustics#45]
Combining `Rc` with `RefCell` results in enabling multiple mutable references (with mutable borrow checking at runtime). This could enable reuse of individuals in a population when appropriate. 

For example, when using stochastic parent selection methods, the same individuals could be sampled to produce offspring.

**Comment by ov-kevin** [comment]
These smart pointer types do not seem to be very useful for this use case. Using only `Rc` will prevent mutability needed for Mutation and combining `Rc` and `RefCell` will incur an unnecessary runtime cost. Recombination operators can simply use immutable references and Mutation operators can use mutable references without issue by correctly using ownership and isolating the immutable and mutable references within the appropriate operator scope.
